# Generated by Django 3.0 on 2019-12-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftexchanger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin_of',
            field=models.ManyToManyField(to='giftexchanger.GiftExchange'),
        ),
    ]
