# Generated by Django 2.2.8 on 2019-12-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftexchanger', '0002_userprofile_admin_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftexchange',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('closed', 'closed')], default='pending', max_length=20),
        ),
    ]
